name: Publish npm package

on:
  push:
    tags: v*

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - name: Get version from tag
      id: get_version
      # "refs/tags/v" is 11 characters
      run: |
        versionNumber=${GITHUB_REF:11}
        echo "::set-output name=version_number::$versionNumber"
        
    - name: checkout code
      uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        registry-url: 'https://registry.npmjs.org'

    - name: Create npm package
      run: |
        cd src
        npm version ${{ steps.get_version.outputs.version_number }}
        npm pack
    
    - name: Publish package
      run: |
        cd src
        npm publish --provenance --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}